import 'dart:math';

String getRandomElement<String>(List<String> list) {
    final random = new Random();
    var i = random.nextInt(list.length);
    return list[i];
}

double getRandomDoubleElement<double>(List<double> list) {
    final random = new Random();
    var i = random.nextInt(list.length);
    return list[i];
}

String pickWord(){
  String titulo = getRandomElement(sustantivos);
  return titulo;
}

List<String> sustantivos = [
  'Barco',
  'Balón',
  'Casa',
  'Lampara',
  "Tren",
  "Oveja",
  "Cohete",
  "Dulce",
  "Pera",
  "Manzana",
  "Cereza",
  "Saturno",
  "Osito de peluche",
  "Pato",
  "Conejo",
  "Pollito",
  "Gato",
  "Girasol",
  "Estrella",
  "Ballena",
  "Árbol",
  "Dragón",
  "Sol",
  "Chinita Arlequín",
  "Camara",
  "Queso",
  "Cono de helado",
  "Bolsa de compras",
  "Taza de cafe",
  "Trozo de sandia",
  "Paleta de helado",
  "Reloj",
  "Isla",
  "Pez",
  "Auto",
  "Bombilla",
  "Hamburguesa",
  "Dona",
  "Sandwich",
  "Audifonos",
  "Cerdo",
  "Cabra",
  "Caballo",
  "Frutilla",
  "Brocoli",
  "Rosa",
  "Tulipán",
  "Lagartija",
  "Paloma",
  "Palmera",
  "Zorro",
  "Payaso",
  "Fantasma",
  "Alien",
  "Pulpo",
  "Robot",
  "Mono",
  "Gorila",
  "Lobo",
  "Mapache",
  "Leon",
  "Tigre",
  "Unicornio",
  "Zebra",
  "Alce",
  "Jaguar",
  "Toro",
  "Jabalí",
  "Camello",
  "Alpaca",
  "Jirafa",
  "Elefante",
  "Rinoceronte",
  "Hipopotamo",
  "Ratón",
  "Ardilla",
  "Puercoespín",
  "Murciélago",
  "Oso",
  "Koala",
  "Panda",
  "Oso perezoso",
  "Nutria",
  "Zorrillo",
  "Kanguro",
  "Pavo",
  "Gallina",
  "Gallo",
  "Pingüino",
  "Alcón",
  "Águila",
  "Cisne",
  "Flamenco",
  "Pavo real",
  "Guacamayo",
  "Rana",
  "Cocodrilo",
  "Tortuga",
  "Serpiente",
  "Tiranosaurio rex",
  "Delfin",
  "Pez globo",
  "Tiburón",
  "Caracol",
  "Mariposa",
  "Oruga",
  "Hormiga",
  "Abeja",
  "Saltamontes",
  "Araña",
  "Escorpión",
  "Zancudo",
  "Cactus",
  "Piña"];